"""Ontology-aligned labels and Turkish display names for campaign annotation."""

from __future__ import annotations


PRODUCT_CATEGORIES = (
    "card",
    "housing_finance",
    "vehicle_finance",
    "consumer_finance",
    "shopping_finance",
    "education_finance",
    "land_finance",
    "workplace_finance",
    "urban_transformation_finance",
    "agriculture_finance",
    "commercial_finance",
    "digital_finance",
    "sustainable_finance",
    "investment_product",
    "participation_account",
    "insurance_takaful",
    "other_finance",
    "other",
    "needs_review",
)

CAMPAIGN_MECHANICS = (
    "installment",
    "discount",
    "cashback",
    "reward_points",
    "referral",
    "loyalty_membership",
    "promo_code",
    "gift_voucher",
    "draw_lottery",
    "other",
)

TARGET_SEGMENTS = (
    "new_customer",
    "existing_customer",
    "salary_customer",
    "youth_student",
    "commercial_sme",
    "farmer",
    "cardholder",
    "digital_customer",
    "other",
)

CHANNELS = (
    "mobile",
    "internet_branch",
    "physical_branch",
    "card_pos",
    "ecommerce",
    "atm",
    "call_center",
    "all_channels",
    "unspecified",
)

BENEFITS = (
    "zero_profit_rate",
    "special_profit_rate",
    "fee_exemption",
    "free_insurance",
    "payment_deferral",
    "extra_installment",
    "gift_voucher",
    "free_service",
    "other",
)

REQUIREMENTS = (
    "minimum_spend",
    "application_required",
    "promo_code_required",
    "automatic_payment_instruction",
    "first_transaction",
    "limited_stock",
    "date_limited",
    "specific_merchant",
    "specific_card",
    "other",
)

DISPLAY_NAMES = {
    "card": "Kart",
    "housing_finance": "Konut Finansmanı",
    "vehicle_finance": "Taşıt Finansmanı",
    "consumer_finance": "İhtiyaç Finansmanı",
    "shopping_finance": "Alışveriş Finansmanı",
    "education_finance": "Eğitim Finansmanı",
    "land_finance": "Arsa Finansmanı",
    "workplace_finance": "İş Yeri Finansmanı",
    "urban_transformation_finance": "Kentsel Dönüşüm Finansmanı",
    "agriculture_finance": "Tarım Finansmanı",
    "commercial_finance": "Ticari/KOBİ Finansmanı",
    "digital_finance": "Dijital Finansman",
    "sustainable_finance": "Sürdürülebilir/Yeşil Finansman",
    "investment_product": "Yatırım Ürünü",
    "participation_account": "Katılma Hesabı",
    "insurance_takaful": "Sigorta/Tekafül",
    "other_finance": "Diğer Finansman",
    "other": "Diğer",
    "needs_review": "Kararsız - İnceleme Gerekli",
    "installment": "Taksit",
    "discount": "İndirim",
    "cashback": "Nakit İade",
    "reward_points": "Puan Kazanımı",
    "referral": "Davet Et Kazan",
    "loyalty_membership": "Sadakat/Üyelik Programı",
    "promo_code": "Promosyon/Kupon Kodu",
    "gift_voucher": "Hediye Çeki",
    "draw_lottery": "Çekiliş",
    "new_customer": "Yeni Müşteri",
    "existing_customer": "Mevcut Müşteri",
    "salary_customer": "Maaş Müşterisi",
    "youth_student": "Genç/Öğrenci",
    "commercial_sme": "Ticari/KOBİ Müşterisi",
    "farmer": "Çiftçi/Tarım Müşterisi",
    "cardholder": "Kart Sahibi",
    "digital_customer": "Dijital Müşteri",
    "mobile": "Mobil Uygulama",
    "internet_branch": "İnternet Şubesi",
    "physical_branch": "Fiziksel Şube",
    "card_pos": "Kart/POS",
    "ecommerce": "E-ticaret/Web Sitesi",
    "atm": "ATM",
    "call_center": "Çağrı Merkezi",
    "all_channels": "Tüm Kanallar",
    "unspecified": "Belirtilmemiş",
    "zero_profit_rate": "%0 Kâr Payı",
    "special_profit_rate": "Avantajlı Kâr Payı",
    "fee_exemption": "Masraf/Ücret Muafiyeti",
    "free_insurance": "Ücretsiz Sigorta",
    "payment_deferral": "Ödeme/Taksit Erteleme",
    "extra_installment": "Ek/Vade Farksız Taksit",
    "free_service": "Ücretsiz Hizmet",
    "minimum_spend": "Minimum Harcama",
    "application_required": "Kampanyaya Katılım/Başvuru",
    "promo_code_required": "Promosyon Kodu Kullanımı",
    "automatic_payment_instruction": "Otomatik Ödeme Talimatı",
    "first_transaction": "İlk İşlem Şartı",
    "limited_stock": "Stoklarla Sınırlı",
    "date_limited": "Tarih/Süre Sınırı",
    "specific_merchant": "Belirli Üye İşyeri",
    "specific_card": "Belirli Kart Kullanımı",
}


def display_name(value: str) -> str:
    return DISPLAY_NAMES.get(value, value.replace("_", " ").title())
